package com.asdacap.ea4k.gp

import com.asdacap.ea4k.gp.functional.NodeFunction
import com.fasterxml.jackson.databind.JsonNode
import kotlin.reflect.jvm.jvmErasure
import kotlin.reflect.jvm.reflect

/**
 * A tree node that always return the same value, which is generated by a generator function in its factory.
 * The value needs to be Json serializable
 */
class GeneratorTreeNode<R>(
    val constant: R,
    override val factory: TreeNodeFactory<NodeFunction<R>>,
): TreeNode<NodeFunction<R>>() {
    override val state: JsonNode by lazy {
        val value = objectMapper.createObjectNode()
        value.set<JsonNode>("constant", objectMapper.valueToTree(constant))
        value
    }

    override fun evaluate(): NodeFunction<R> {
        return NodeFunction { constant }
    }

    override fun replaceChildren(newChildren: List<TreeNode<*>>): TreeNode<NodeFunction<R>> {
        return GeneratorTreeNode(constant, factory)
    }

    class Factory<R: Any>(
        val generator: () -> R,
        val kotlinReturnType: Class<*> = generator.reflect()!!.returnType.jvmErasure.java,
        override val returnType: NodeType = KotlinNodeType(generator.reflect()!!.returnType)
    ) : TreeNodeFactory<NodeFunction<R>> {
        override fun createNode(children: List<TreeNode<*>>, state: JsonNode?): TreeNode<NodeFunction<R>> {
            val constant = if (state == null) {
                generator()
            } else {
                val constantState = state.get("constant")
                objectMapper.treeToValue(constantState, kotlinReturnType) as R
            }

            return GeneratorTreeNode(constant, this)
        }

        override val args: List<NodeType> = listOf()
    }
}
